/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import  java.util.Date;  
import Utilitarios.ModeloTabela;
import Utilitarios.conectaBanco;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author italo
 */
public class FolhaDePagamento extends javax.swing.JFrame {

    conectaBanco conecta= new conectaBanco();
    ArrayList dados=new ArrayList();
    String[] Colunas=new String[]{"Nºinscrição","Modalidade","Dia","Horário","Professor","Aluno","RG Do Aluno","Janeiro","Fevereiro","Março",
                                  "Abril","Maio","Junho","Julho","Agosto","Setembro","Outubro","Novembro","Dezembro"};
    /**
     * Creates new form FolhaDePagamento
     */
    public FolhaDePagamento() {
        initComponents();
        conecta.conexao();
        preencherTabelaPagamentoAlunos();
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox2 = new javax.swing.JCheckBox();
        jDateChooser5 = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        jDateChooser7 = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jTextFieldNomeAluno = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldRgAluno = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTablePagamentoAlunos = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jDateChooserJaneiro = new com.toedter.calendar.JDateChooser();
        jDateChooserFevereiro = new com.toedter.calendar.JDateChooser();
        jDateChooserMarco = new com.toedter.calendar.JDateChooser();
        jDateChooserAbril = new com.toedter.calendar.JDateChooser();
        jDateChooserMaio = new com.toedter.calendar.JDateChooser();
        jDateChooserJunho = new com.toedter.calendar.JDateChooser();
        jDateChooserAgosto = new com.toedter.calendar.JDateChooser();
        jDateChooserSetembro = new com.toedter.calendar.JDateChooser();
        jDateChooserOutubro = new com.toedter.calendar.JDateChooser();
        jDateChooserJulho = new com.toedter.calendar.JDateChooser();
        jDateChooserNovembro = new com.toedter.calendar.JDateChooser();
        jDateChooserDezembro = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jTextFieldNumeroDeInscricao = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();

        jCheckBox2.setText("jCheckBox2");

        jLabel8.setText("Janeiro:");

        jLabel10.setText("Janeiro:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton1.setText("Confirmar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextFieldNomeAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeAlunoActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome do aluno:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("FOLHA DE PAGAMENTO");

        jLabel3.setText("RG do aluno:");

        jTablePagamentoAlunos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", "", null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTablePagamentoAlunos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePagamentoAlunosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTablePagamentoAlunos);

        jLabel4.setText("Modalidade:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel7.setText("Junho:");

        jLabel9.setText("Janeiro:");

        jLabel11.setText("Fevereiro:");

        jLabel12.setText("Março:");

        jLabel13.setText("Abril:");

        jLabel14.setText("Maio:");

        jLabel15.setText("Julho:");

        jLabel16.setText("Agosto:");

        jLabel17.setText("Setembro:");

        jLabel18.setText("Outubro:");

        jLabel19.setText("Novembro:");

        jLabel20.setText("Dezembro:");

        jLabel5.setText("Dia:");

        jLabel6.setText("Hórario:");

        jLabel21.setText("Professor:");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton2.setText("Pesquisar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextFieldNumeroDeInscricao.setEnabled(false);

        jLabel22.setText("Nº de inscrição:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jDateChooserJulho, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateChooserAgosto, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateChooserSetembro, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateChooserOutubro, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateChooserNovembro, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateChooserDezembro, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jDateChooserJaneiro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDateChooserFevereiro, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDateChooserMarco, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDateChooserAbril, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDateChooserMaio, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jDateChooserJunho, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldNumeroDeInscricao))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldNomeAluno)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldRgAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel2)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel22))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldNomeAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldRgAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldNumeroDeInscricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel21)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jDateChooserJaneiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooserFevereiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooserMarco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooserAbril, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooserMaio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooserJunho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jDateChooserJulho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooserAgosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooserSetembro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooserOutubro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooserNovembro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooserDezembro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       if((jTextFieldNumeroDeInscricao.getText().isEmpty())){
            JOptionPane.showMessageDialog(rootPane, "Preencha todos os campos obrigatorios!");
        }
        else{
            try {
                SimpleDateFormat DateFormat = new SimpleDateFormat("dd-MM-yyyy");
                PreparedStatement pst=conecta.conn.prepareStatement("update FOLHADEPAGAMENTO set JANEIRO=?,FEVEREIRO=?,"
                        + "MARCO=?,ABRIL=?,MAIO=?,JUNHO=?,JULHO=?,AGOSTO=?,SETEMBRO=?,OUTUBRO=?,NOVEMBRO=?,DEZEMBRO=? "
                        + "where numeroDeInscricao=?");
                if(jDateChooserJaneiro.getDate()==null){
                    pst.setString(1, null); 
                }
                else{
                    pst.setString(1, DateFormat.format(jDateChooserJaneiro.getDate()));
                }
                if(jDateChooserFevereiro.getDate()==null){
                    pst.setString(2, null); 
                }
                else{
                pst.setString(2, DateFormat.format(jDateChooserFevereiro.getDate()));
                }
                if(jDateChooserMarco.getDate()==null){
                    pst.setString(3, null); 
                }
                else{
                pst.setString(3, DateFormat.format(jDateChooserMarco.getDate()));
                }
                if(jDateChooserAbril.getDate()==null){
                    pst.setString(4, null); 
                }
                else{
                pst.setString(4, DateFormat.format(jDateChooserAbril.getDate()));
                }
                if(jDateChooserMaio.getDate()==null){
                    pst.setString(5, null); 
                }
                else{
                pst.setString(5, DateFormat.format(jDateChooserMaio.getDate()));
                }
                if(jDateChooserJunho.getDate()==null){
                    pst.setString(6, null); 
                }
                else{
                pst.setString(6, DateFormat.format(jDateChooserJunho.getDate()));
                }
                if(jDateChooserJulho.getDate()==null){
                    pst.setString(7, null); 
                }
                else{
                pst.setString(7, DateFormat.format(jDateChooserJulho.getDate()));
                }
                if(jDateChooserAgosto.getDate()==null){
                    pst.setString(8, null); 
                }
                else{
                pst.setString(8, DateFormat.format(jDateChooserAgosto.getDate()));
                }
                if(jDateChooserSetembro.getDate()==null){
                    pst.setString(9, null); 
                }
                else{
                pst.setString(9, DateFormat.format(jDateChooserSetembro.getDate()));
                }
                if(jDateChooserOutubro.getDate()==null){
                    pst.setString(10, null); 
                }
                else{
                pst.setString(10, DateFormat.format(jDateChooserOutubro.getDate()));
                }
                if(jDateChooserNovembro.getDate()==null){
                    pst.setString(11, null); 
                }
                else{
                pst.setString(11, DateFormat.format(jDateChooserNovembro.getDate()));
                }
                if(jDateChooserDezembro.getDate()==null){
                    pst.setString(12, null); 
                }
                else{
                pst.setString(12, DateFormat.format(jDateChooserDezembro.getDate()));
                }
                pst.setString(13, jTextFieldNumeroDeInscricao.getText());
            
                pst.executeUpdate();
 
                JOptionPane.showMessageDialog(rootPane, "Salvo com sucesso!");

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(rootPane, "Erro na inserção!\n Erro:"+ex);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTablePagamentoAlunosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePagamentoAlunosMouseClicked
        ModeloTabela ModeloTabela=new ModeloTabela(dados,Colunas);
        jTablePagamentoAlunos.getModel();
        int index = jTablePagamentoAlunos.getSelectedRow();
        Date Janeiro=null,Fevereiro=null,Marco=null,Abril=null,Maio=null,Junho=null,Julho=null,Agosto=null,Setembro=null,Outubro=null,Novembro=null,Dezembro=null;
        
        String numeroDeInscricao=""+jTablePagamentoAlunos.getValueAt(jTablePagamentoAlunos.getSelectedRow(), 0);
        jTextFieldNumeroDeInscricao.setText(numeroDeInscricao);
        String NomeAluno=""+jTablePagamentoAlunos.getValueAt(jTablePagamentoAlunos.getSelectedRow(), 5);
        jTextFieldNomeAluno.setText(NomeAluno);
        String RgAluno=""+jTablePagamentoAlunos.getValueAt(jTablePagamentoAlunos.getSelectedRow(), 6);
        jTextFieldRgAluno.setText(RgAluno);
        try {
            Janeiro = new SimpleDateFormat("dd-MM-yyyy").parse((String)jTablePagamentoAlunos.getValueAt(index, 7));
            Fevereiro = new SimpleDateFormat("dd-MM-yyyy").parse((String)jTablePagamentoAlunos.getValueAt(index, 8));
            Marco = new SimpleDateFormat("dd-MM-yyyy").parse((String)jTablePagamentoAlunos.getValueAt(index, 9));
            Abril = new SimpleDateFormat("dd-MM-yyyy").parse((String)jTablePagamentoAlunos.getValueAt(index, 10));
            Maio = new SimpleDateFormat("dd-MM-yyyy").parse((String)jTablePagamentoAlunos.getValueAt(index, 11));
            Junho = new SimpleDateFormat("dd-MM-yyyy").parse((String)jTablePagamentoAlunos.getValueAt(index, 12));
            Julho = new SimpleDateFormat("dd-MM-yyyy").parse((String)jTablePagamentoAlunos.getValueAt(index, 13));
            Agosto = new SimpleDateFormat("dd-MM-yyyy").parse((String)jTablePagamentoAlunos.getValueAt(index, 14));
            Setembro = new SimpleDateFormat("dd-MM-yyyy").parse((String)jTablePagamentoAlunos.getValueAt(index, 15));
            Outubro = new SimpleDateFormat("dd-MM-yyyy").parse((String)jTablePagamentoAlunos.getValueAt(index, 16));
            Novembro = new SimpleDateFormat("dd-MM-yyyy").parse((String)jTablePagamentoAlunos.getValueAt(index, 17));
            Dezembro = new SimpleDateFormat("dd-MM-yyyy").parse((String)jTablePagamentoAlunos.getValueAt(index, 18));
        } catch (NullPointerException ex) {
            System.out.println("oi");
        } catch (ParseException ex) {
            Logger.getLogger(FolhaDePagamento.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(Janeiro==null){
            jDateChooserJaneiro.setDate(null);
        }
        else{
            jDateChooserJaneiro.setDate(Janeiro);
        }
        if(Fevereiro==null){
            jDateChooserFevereiro.setDate(null);
        }
        else{
            jDateChooserFevereiro.setDate(Fevereiro);
        }
        if(Marco==null){
            jDateChooserMarco.setDate(null);
        }
        else{
            jDateChooserMarco.setDate(Marco);
        }
        if(Abril==null){
            jDateChooserAbril.setDate(null);
        }
        else{
            jDateChooserAbril.setDate(Abril);
        }
        if(Maio==null){
            jDateChooserMaio.setDate(null);
        }
        else{
            jDateChooserMaio.setDate(Maio);
        }
        if(Junho==null){
            jDateChooserJunho.setDate(null);
        }
        else{
            jDateChooserJunho.setDate(Junho);
        }
        if(Julho==null){
            jDateChooserJulho.setDate(null);
        }
        else{
            jDateChooserJulho.setDate(Julho);
        }
        if(Agosto==null){
            jDateChooserAgosto.setDate(null);
        }
        else{
            jDateChooserAgosto.setDate(Agosto);
        }
        if(Setembro==null){
            jDateChooserSetembro.setDate(null);
        }
        else{
            jDateChooserSetembro.setDate(Setembro);
        }
        if(Outubro==null){
            jDateChooserOutubro.setDate(null);
        }
        else{
            jDateChooserOutubro.setDate(Outubro);
        }
        if(Novembro==null){
            jDateChooserNovembro.setDate(null);
        }
        else{
            jDateChooserNovembro.setDate(Novembro);
        }
        if(Dezembro==null){
            jDateChooserDezembro.setDate(null);
        }
        else{
            jDateChooserDezembro.setDate(Dezembro);
        }
    }//GEN-LAST:event_jTablePagamentoAlunosMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextFieldNomeAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeAlunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeAlunoActionPerformed
    public void preencherTabela(String SQL){
        conecta.executaSQL(SQL);
        try {
            conecta.rs.first();
            do{
            dados.add(new Object[]{conecta.rs.getInt("NUMERODEINSCRICAO"),conecta.rs.getString("MODALIDADE"),conecta.rs.getString("DIA"),
                conecta.rs.getString("HORARIO"),conecta.rs.getString("PROFESSOR"),conecta.rs.getString("NOME_ALUNO"),
                conecta.rs.getString("RG_ALUNO"),conecta.rs.getString("JANEIRO"),conecta.rs.getString("FEVEREIRO"),
                conecta.rs.getString("MARCO"),conecta.rs.getString("ABRIL"),conecta.rs.getString("MAIO"),
                conecta.rs.getString("JUNHO"),conecta.rs.getString("JULHO"),conecta.rs.getString("AGOSTO"),
                conecta.rs.getString("SETEMBRO"),conecta.rs.getString("OUTUBRO"),conecta.rs.getString("NOVEMBRO"),conecta.rs.getString("DEZEMBRO")});
            }while(conecta.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao preencher a tabela ou tabela vazia (ArrayList)!\n Erro:"+ex);
        }
        ModeloTabela ModeloTabela=new ModeloTabela(dados,Colunas);
        jTablePagamentoAlunos.setModel(ModeloTabela);
        /*jTableAlunos.getColumnModel().getColumn(0).setPreferredWidth(65);
        jTableAlunos.getColumnModel().getColumn(1).setPreferredWidth(120);
        jTableAlunos.getColumnModel().getColumn(2).setPreferredWidth(120);
        jTableAlunos.getColumnModel().getColumn(3).setPreferredWidth(65);
        jTableAlunos.getColumnModel().getColumn(4).setPreferredWidth(120);
        jTableAlunos.getColumnModel().getColumn(5).setPreferredWidth(120);
        jTableAlunos.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);*/
    }
    public void preencherTabelaPagamentoAlunos(){
        preencherTabela("select * from FOLHADEPAGAMENTO");           
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FolhaDePagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FolhaDePagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FolhaDePagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FolhaDePagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FolhaDePagamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private com.toedter.calendar.JDateChooser jDateChooser5;
    private com.toedter.calendar.JDateChooser jDateChooser7;
    private com.toedter.calendar.JDateChooser jDateChooserAbril;
    private com.toedter.calendar.JDateChooser jDateChooserAgosto;
    private com.toedter.calendar.JDateChooser jDateChooserDezembro;
    private com.toedter.calendar.JDateChooser jDateChooserFevereiro;
    private com.toedter.calendar.JDateChooser jDateChooserJaneiro;
    private com.toedter.calendar.JDateChooser jDateChooserJulho;
    private com.toedter.calendar.JDateChooser jDateChooserJunho;
    private com.toedter.calendar.JDateChooser jDateChooserMaio;
    private com.toedter.calendar.JDateChooser jDateChooserMarco;
    private com.toedter.calendar.JDateChooser jDateChooserNovembro;
    private com.toedter.calendar.JDateChooser jDateChooserOutubro;
    private com.toedter.calendar.JDateChooser jDateChooserSetembro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTablePagamentoAlunos;
    private javax.swing.JTextField jTextFieldNomeAluno;
    private javax.swing.JTextField jTextFieldNumeroDeInscricao;
    private javax.swing.JTextField jTextFieldRgAluno;
    // End of variables declaration//GEN-END:variables
}
